[tool.poetry]
name = "shorpy"
version = "0.1.0"
description = ""
authors = ["shotowon <sanzhar.maratov@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic-settings = "^2.7.1"
python-json-logger = "^3.2.1"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
colorlog = "^6.9.0"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
