"""url make alias field unique

Revision ID: 3f2d7b51153c
Revises: 80fbacf903f6
Create Date: 2025-01-12 20:55:12.952203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f2d7b51153c"
down_revision: Union[str, None] = "80fbacf903f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "url", ["alias"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "url", type_="unique")
    # ### end Alembic commands ###
